<?xml version="1.0"?>
<!-- Joint angles, link lengths and mass all found from Automata documentation -->
<robot name="simpleEVA" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Import variables -->	
	<xacro:include filename="$(find simple_eva_description)/urdf/variables.xacro"/>
	<!-- Import macros -->
	<xacro:include filename="$(find simple_eva_description)/urdf/macros.xacro"/>
	<!-- Import materials/colours --> 
	<xacro:include filename="$(find simple_eva_description)/urdf/materials.xacro"/>
	
	<!-- 1st link -->
	<link name="link1">
		<xacro:boxInertial m="${m_total*(l1_l/l_total)}" l="${l1_l}" d="${l1_d}" w="${l1_w}"/>
		<xacro:boxGeometry name="link1" l="${l1_l}" d="${l1_d}" w="${l1_w}" XYZ="0 0 ${l1_l/2}" RPY="0 0 0" colour="offWhite"/>
	</link>
	
	<!-- 1st joint --> 
	<joint name="joint1" type="revolute">
		<parent link="link1"/>
		<child link="link2"/>
		<xacro:jointLimits upper="179" lower="-179"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 ${l1_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- "control box" -->
	<link name="controlBox">
		<xacro:boxGeometry name="controlBox" l="${cb_l}" w="${cb_w}" d="${cb_d}" XYZ="${l1_d/2} 0 ${cb_l/2}" RPY="0 0 0" colour="darkGrey"/>
	</link>
	
	<joint name="cBoxToLink1" type="fixed">
		<parent link="link1"/>
		<child link="controlBox"/>
	</joint>
		
	<!-- 2nd link -->
	<link name="link2">
		<xacro:cylinderInertial m="${m_total*(l2_l/l_total)}" l="${l2_l}" r="${l2_r}"/>
		<xacro:cylinderGeometry name="link2" l="${l2_l}" r="${l2_r}" XYZ="0 ${l2_r} ${l2_l/2}" RPY="0 0 0" colour="offWhite"/>
	</link>
	
	<!-- 2nd joint -->
	<joint name="joint2" type="revolute">
		<parent link="link2"/>
		<child link="link3"/>
		<xacro:jointLimits upper="70" lower="-155"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${l2_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 3rd link -->
	<link name="link3">
		<xacro:cylinderInertial m="${m_total*(l3_l/l_total)}" l="${l3_l}" r="${l3_r}"/>
		<xacro:cylinderGeometry name="link3" l="${l3_l}" r="${l3_r}" XYZ="0 ${-1*l3_r} ${l2_l}" RPY="0 0 0" colour="offWhite"/>
	</link>
	
	<!-- 3rd joint -->
	<joint name="joint3" type="revolute">
		<parent link="link3"/>
		<child link="link4"/>
		<xacro:jointLimits upper="45" lower="-160"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${l3_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 4th link -->
	<link name="link4">
		<xacro:cylinderInertial m="${m_total*(l4_l/l_total)}" l="${l4_l}" r="${l4_r}"/>
		<xacro:cylinderGeometry name="link4" l="${l4_l}" r="${l4_r}" XYZ="0 ${l4_r} ${l4_l/2}" RPY="0 0 0" colour="offWhite"/>
	</link>
	
	<!-- 4th joint -->
	<joint name="joint4" type="revolute">
		<parent link="link4"/>
		<child link="link5"/>
		<xacro:jointLimits upper="179" lower="-179"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 ${l4_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 5th link -->
	<link name="link5">
		<xacro:cylinderInertial m="${m_total*(l5_l/l_total)}" l="${l5_l}" r="${l5_r}"/>
		<xacro:cylinderGeometry name="link5" l="${l5_l}" r="${l4_r}" XYZ="0 0 ${l5_l/2}" RPY="0 0 0" colour="offWhite"/>
	</link>
	
	<!-- 5th joint -->
	<joint name="joint5" type="revolute">
		<parent link="link5"/>
		<child link="link6"/>
		<xacro:jointLimits upper="10" lower="-155"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${l5_l}" rpy="0 0 0"/>
	</joint>
		
	<!-- 6th link -->
	<link name="link6">
		<xacro:boxInertial m="${m_total*(l6_l/l_total)}" l="${l6_l}" d="${l6_d}" w="${l6_w}"/>
		<xacro:boxGeometry name="link6" l="${l6_l}" d="${l6_d}" w="${l6_w}" XYZ="${l5_r} 0 ${l6_d}" RPY="0 0 0" colour="offWhite"/>
	</link>
	
	<!-- 6th joint -->
	<joint name="joint6" type="revolute">
		<parent link="link6"/>
		<child link="lamp"/>
		<xacro:jointLimits upper="179" lower="-179"/>
		<axis xyz="0 0 1"/>
		<origin xyz="${l5_r} 0 ${l6_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- Lamp -->
	<link name="lamp">
		<xacro:boxGeometry name="lamp" l="${lamp_l}" d="${lamp_d}" w="${lamp_w}" XYZ="0 0 ${lamp_l/2}" RPY="0 0 0" colour="black"/>
	</link>
	
	<!-- "bulb" -->
	<link name="bulb">
		<xacro:cylinderGeometry name="bulb" l="${bulb_l}" r="${bulb_r}" XYZ="0 0 ${lamp_l-(bulb_l/2)}" RPY="0 0 0" colour="yellow"/>
	</link>
	
	<joint name="bulbToLamp" type="fixed">
		<parent link="lamp"/>
		<child link="bulb"/>
	</joint>
</robot>