<?xml version="1.0"?>
<!-- Joint angles, link lengths and mass all found from Automata documentation -->
<robot name="simpleEVA" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Import variables -->	
	<xacro:include filename="$(find simple_eva_description)/urdf/variables.xacro"/>
	<!-- Import macros -->
	<xacro:include filename="$(find simple_eva_description)/urdf/macros.xacro"/>
	
	<!-- 1st link -->
	<link name="link1">
		<xacro:boxInertial m="${m_total*(l1_l/l_total)}" l="${l1_l}" d="${l1_d}" w="${l1_w}"/>
		<xacro:boxGeometry name="link1" l="${l1_l}" d="${l1_d}" w="${l1_w}" XYZ="0 0 ${l1_l/2}" RPY="0 0 0"/>
	</link>
	
	<!-- 1st joint --> 
	<joint name="joint1" type="revolute">
		<parent link="link1"/>
		<child link="link2"/>
		<xacro:jointLimits upper="180" lower="-180"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 ${l1_l}" rpy="0 0 0"/>
	</joint>
		
	<!-- 2nd link -->
	<link name="link2">
		<xacro:cylinderInertial m="${m_total*(l2_l/l_total)}" l="${l2_l}" r="${l2_r}"/>
		<xacro:cylinderGeometry name="link2" l="${l2_l}" r="${l2_r}" XYZ="0 ${l2_r} ${l2_l/2}" RPY="0 0 0"/>
	</link>
	
	<!-- 2nd joint -->
	<joint name="joint2" type="revolute">
		<parent link="link2"/>
		<child link="link3"/>
		<xacro:jointLimits upper="74" lower="-159"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${l2_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 3rd link -->
	<link name="link3">
		<xacro:cylinderInertial m="${m_total*(l3_l/l_total)}" l="${l3_l}" r="${l3_r}"/>
		<xacro:cylinderGeometry name="link3" l="${l3_l}" r="${l3_r}" XYZ="${l3_l/2} ${-1*l3_r} 0" RPY="0 ${pi/2} 0"/>
	</link>
	
	<!-- 3rd joint -->
	<joint name="joint3" type="revolute">
		<parent link="link3"/>
		<child link="link4"/>
		<xacro:jointLimits upper="47" lower="-165"/>
		<axis xyz="0 1 0"/>
		<origin xyz="${l3_l} 0 0" rpy="0 0 0"/>
	</joint>
	
	<!-- 4th link -->
	<link name="link4">
		<xacro:cylinderInertial m="${m_total*(l4_l/l_total)}" l="${l4_l}" r="${l4_r}"/>
		<xacro:cylinderGeometry name="link4" l="${l4_l}" r="${l4_r}" XYZ="${l4_l/2} ${l4_r} 0" RPY="0 ${pi/2} 0"/>
	</link>
	
	<!-- 4th joint -->
	<joint name="joint4" type="revolute">
		<parent link="link4"/>
		<child link="link5"/>
		<xacro:jointLimits upper="180" lower="-180"/>
		<axis xyz="1 0 0"/>
		<origin xyz="${l4_l} 0 0" rpy="0 0 0"/>
	</joint>
	
	<!-- 5th link -->
	<link name="link5">
		<xacro:cylinderInertial m="${m_total*(l5_l/l_total)}" l="${l5_l}" r="${l5_r}"/>
		<xacro:cylinderGeometry name="link5" l="${l5_l}" r="${l4_r}" XYZ="${l5_l/2} 0 0" RPY="0 ${pi/2} 0"/>
	</link>
	
	<!-- 5th joint -->
	<joint name="joint5" type="revolute">
		<parent link="link5"/>
		<child link="link6"/>
		<xacro:jointLimits upper="11" lower="-159"/>
		<axis xyz="0 1 0"/>
		<origin xyz="${l5_l} 0 0" rpy="0 0 0"/>
	</joint>
		
	<!-- 6th link -->
	<link name="link6">
		<xacro:boxInertial m="${m_total*(l6_l/l_total)}" l="${l6_l}" d="${l6_d}" w="${l6_w}"/>
		<xacro:boxGeometry name="link6" l="${l6_l}" d="${l6_d}" w="${l6_w}" XYZ="${l6_l/2} 0 0" RPY="0 ${pi/2} 0"/>
	</link>
	
	<!-- Lamp -->
	<!--<material name="yellow"
	<link name="lamp">
		<xacro:boxGeometry name="lamp" l="${lamp_l}" d="${lamp_d}" w="${lamp_w}" XYZ=
	-->
</robot>